FROM careywong/myurls:latest
# https://github.com/CareyWang/MyUrls
# docker run -d --restart always --name myurls careywong/myurls:latest -domain example.com -port 8002 -conn 127.0.0.1:6379 -passwd '' -ttl 90

# 8002 短链接
# 6379 redis
EXPOSE 8002 6379